CREATE TABLE Groups (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Description TEXT NOT NULL,
    CreatorID INTEGER REFERENCES Users(ID),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
