CREATE TABLE IF NOT EXISTS GroupUsers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GroupID INTEGER,
    UserID INTEGER,
    FOREIGN KEY (GroupID) REFERENCES Groups(ID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

